import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Grid from "@mui/system/Grid";
import Dashboard from "./pages/dashboard/page";
import Sidebar from "./pages/sidebar/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full flex">
          <div className="lg:w-[20%]">
            <Sidebar />
          </div>
          <div className="w-full lg:w-[80%]">
            <div>
              <Dashboard />
            </div>
            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
